# Конструкция `try - except`
#tryexcept
***
```python
try:
	# попытка
except (ExceptName1, ExceptName2, ExceptName3):
	# при наступлении одного из перечисленных исключений
except ExceptName:
	# при наступлении конкретного исключения
except:
	# при наступлении любого, ранее не указанного исключения
else:
	# если 
finally:
```

## Список исключений
***
-   `IndexError`: возникает, когда индекс (например, для элемента списка) указан неправильно (выходит за границы допустимого диапазона)
-   `KeyError`: возникает при неверно указанном ключе словаря
-   `NameError`: возникает, если не удается найти переменную с некоторым названием
-   `SyntaxError`: возникает при наличии в исходном коде синтаксических ошибок
-   `TypeError`: возникает при несоответствии типов, когда для обработки требуется значение определенного типа, а передается значение другого типа
-   `FileNotFoundError`: возникает при открытии несуществующего файла
-   `ValueError`: возникает, когда в функцию передается аргумент с неподдерживаемым значением
-   `ZeroDivisionError`: возникает при попытке выполнить деление на ноль